version: '3.8'
services:

  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: em
      POSTGRES_PASSWORD: em
      POSTGRES_DB: eventmanager
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
    db_data: